# what do you mean by __init__{} method in python ?Givean example of it
=>It is Constructor of python class
__init__ it is called when object of class is constructed

In [12]:
class student:
    def __init__(self,name,age,branch):
        self.name=name
        self.age=age
        self.branch=branch
    def print_name(self):
        print("Name",self.name)
        print("Age",self.age)
        print("branch",self.branch)
        

In [13]:
student1=student("Nilesh",34,"ETC")

In [14]:
student1.print_name()

Name Nilesh
Age 34
branch ETC


# what do you mean by inheritance in python?give Example of it.

In [19]:
class fruit:
    def __init__(self):
        print("I Am fruit")
class citrus(fruit):
    def __init__(self):
        super().__init__()
        print("I am citrus")
lemon=citrus()


I Am fruit
I am citrus
I Am fruit
I Am red and heart shape


In [20]:
class apple(fruit):
    def __init__(self):
        super().__init__()
        print("I Am red and heart shape")
a1=apple()

I Am fruit
I Am red and heart shape


In [22]:
import numpy as np
oned_array=np.array([1,2,3,4,5])
twod_array=np.array([[1,2,3],[4,5,6]])
print("1-D Array",oned_array)
print("2-D Array",twod_array)

1-D Array [1 2 3 4 5]
2-D Array [[1 2 3]
 [4 5 6]]


In [24]:
import numpy as np
a1=np.array([12,45,78,98,100])
print(a1.argsort())

[0 1 2 3 4]


In [28]:
import pandas as pd
l1=[1,2,3,4]
df={'fruit':['Apple','Orange','lemon']}
print(pd.DataFrame(l1))
print(pd.DataFrame(df))


   0
0  1
1  2
2  3
3  4
    fruit
0   Apple
1  Orange
2   lemon


In [36]:
import numpy as np
a1=np.arange(0,10)
a1[a1%2==1]=-1
a1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [40]:
import numpy as np
a1=np.arange(0,10)
a2=np.arange(0,5)
for i in a1:
    if i in a2:
        print(a2)
        break
np.intersect1d(a1,a2)

[0 1 2 3 4]


array([0, 1, 2, 3, 4])

In [43]:
import pandas as pd
a1=pd.Series(['hello','Nilesh','jeevan','a10'])
print(a1.map(lambda x :x.title()))

0     Hello
1    Nilesh
2    Jeevan
3       A10
dtype: object


0     Hello
1    Nilesh
2    Jeevan
3       A10
dtype: object
