In [ ]:
## Basic Of Pytorch Librabry

In [2]:
import torch
import torchvision
import torchvision.transforms as transform

In [4]:
#Creating matrix Using pytorch
x=torch.empty(5,3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [3.5873e-43, 0.0000e+00, 0.0000e+00]])


In [6]:
#Creating matrix randomly uninilized matrix
x=torch.rand(5,3)
print(x)

tensor([[0.1669, 0.6716, 0.4130],
        [0.0520, 0.0220, 0.1315],
        [0.1212, 0.2729, 0.6101],
        [0.0269, 0.0491, 0.5854],
        [0.8436, 0.3176, 0.5691]])


In [7]:
#Creating Matrix filling With Zeros
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
x=torch.tensor([5,3,3])
print(x)

tensor([5, 3, 3])


In [11]:
x=x.new_ones(5,3,dtype=torch.double)
print(x)
x=torch.randn_like(x,dtype=torch.float)
print(x)



tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.0033,  0.2420,  0.0128],
        [ 0.7096, -1.1446,  0.0728],
        [ 0.3059,  0.6765,  0.1713],
        [ 1.0391, -1.5090,  1.0563],
        [-0.4790, -1.6868, -0.6552]])


In [13]:
y=torch.rand(5,3)
print(x+y)

tensor([[-0.4698,  0.3184,  0.2666],
        [ 1.2187, -0.3179,  0.7268],
        [ 0.5362,  1.5890,  0.4854],
        [ 1.1656, -1.2343,  1.6222],
        [ 0.5091, -0.7207, -0.3020]])
