# Matrix Opeartion

In [10]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print("*"*15)
print("0 row",a[0])
print("*"*15)
print("0 col",a[:,0])
print("*"*15)
print("1 row",a[1])
print("*"*15)
print("1 col",a[:,1])
print("*"*15)
print("2 row",a[2])
print("*"*15)
print("2 col",a[:,2])
print("Diagonal Element of Matrix")
print(a.diagonal(0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
***************
0 row [1 2 3]
***************
0 col [1 4 7]
***************
1 row [4 5 6]
***************
1 col [2 5 8]
***************
2 row [7 8 9]
***************
2 col [3 6 9]
Diagonal Element of Matrix
[1 5 9]


# Array Manulpliation

In [21]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[8,8,8,]])

# Array concatenate

In [27]:
print(np.concatenate((a,b),axis=0))
print("*"*15)
print(np.concatenate((a,b),axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [8 8 8]]
***************
[[1 2 3 7 8 9]
 [4 5 6 8 8 8]]


# Stack array Row-wise(verticallu)

In [23]:
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [8 8 8]]


# Stack array col-wise(Horzontally)

In [24]:
print(np.hstack((a,b)))

[[1 2 3 7 8 9]
 [4 5 6 8 8 8]]


# Combinig Column wise stacked array


In [25]:
np.column_stack((a,b))

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 8, 8, 8]])

# Spliting array

In [34]:
a=np.array([[1,2,3],[4,5,6]])
np.split(a,2,axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [47]:
import numpy as np
import time


def using_list():
    t1=time.time()
    X=range(100000)
    Y=range(100000)
    z=[X[i]*Y[i] for i in range(len(X))]
    return time.time()-t1

def using_numpy():
    t1=time.time()
    a=np.arange(100000)
    b=np.arange(100000)
    c=a*b
    return time.time()-t1
list_time=using_list()
numpy_time=using_numpy()
print(list_time," ",numpy_time)


0.07198262214660645   0.0
