# Initializing Numpy Array

In [4]:
import numpy as np
a=np.array([1,2,3])
b=np.array((1,2,3))
print(a)
print(b)

[1 2 3]
[1 2 3]


In [5]:
b[1]=4

In [6]:
b

array([1, 4, 3])

# np.zeros

In [7]:
import numpy as np
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# np.arange

In [ ]:
# import numpy as np
np.arange(10,25,5)

In [10]:
#np.arange(startnum,endnum,interval)
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

# np.linspace

In [12]:
import numpy as np
np.linspace(5,10,6)

array([ 5.,  6.,  7.,  8.,  9., 10.])

In [13]:
np.linspace(5,10,5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [14]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

# np.full

In [15]:
import numpy as np
c=np.full((3,4),5)
print(c)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [16]:
import numpy as np
np.full((2,4),6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6]])

# Filing RANDOM numbers in a array of dimension x X y

In [20]:
import numpy as np
np.random.random((2,2))

array([[0.46150369, 0.13625116],
       [0.43496395, 0.47170427]])

# Numpy Array inspection
"""Return a tuple consisting of arra dimension .
can also be used to resize the array"""

In [21]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


# array.shape

In [22]:
import numpy as np
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b.shape)

(3, 3)


In [25]:
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


# changing dimesion of array
array.shape
"""Return a tuple consisting of array dimension.Can
 also be used to resize the Array"""

In [27]:
import numpy as np
a=np.array([[1,2,3,4],[4,5,6,7]])
a.shape=(8,1)
print(a)

[[1]
 [2]
 [3]
 [4]
 [4]
 [5]
 [6]
 [7]]


# Array.dtype

In [28]:
import numpy as np
a=np.arange(24,dtype=float)
print(a.size)
print(a.dtype)
b=a.reshape(3,4,2)
b

24
float64


array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.]],

       [[ 8.,  9.],
        [10., 11.],
        [12., 13.],
        [14., 15.]],

       [[16., 17.],
        [18., 19.],
        [20., 21.],
        [22., 23.]]])

In [30]:
#Addition using as np
np.sum([10,20])

30

In [31]:
a,b=10,20
np.sum([a,b])

30

In [32]:
np.sum([[0,1],[0,5]],axis=0)

array([0, 6])

In [33]:
np.sum([[0,1],[0,5]],axis=1)


array([1, 5])

# Matrix Operation 

In [34]:
import numpy as np
mat1=np.array([[1,2,3],[4,5,6],[7,8,9]])
mat2=np.array([[9,8,7],[6,5,4],[3,2,1]])

In [37]:
np.divide(mat1,mat2)

array([[0.11111111, 0.25      , 0.42857143],
       [0.66666667, 1.        , 1.5       ],
       [2.33333333, 4.        , 9.        ]])

In [38]:
np.subtract(mat1,mat2)

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [40]:
np.dot(mat1,mat2)
#matrix multiplication

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [41]:
#Element Wise multipication
np.multiply(mat1,mat2)

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [42]:
np.exp(mat1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [43]:
np.sqrt(mat1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [44]:
np.sin(mat2)

array([[ 0.41211849,  0.98935825,  0.6569866 ],
       [-0.2794155 , -0.95892427, -0.7568025 ],
       [ 0.14112001,  0.90929743,  0.84147098]])

In [45]:
np.log(mat2)

array([[2.19722458, 2.07944154, 1.94591015],
       [1.79175947, 1.60943791, 1.38629436],
       [1.09861229, 0.69314718, 0.        ]])

In [46]:
np.cos(mat1)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

# Array Comparison

# Element-Wise Comparison

In [47]:
import numpy as np
a=[1,2,3]
b=[2,4,4]
c=[1,2,4]
np.equal(a,b)

array([False, False, False])

In [48]:
import numpy as np
a=[1,2,3]
b=[2,4,4]
c=[1,2,4]
np.equal(a,c)

array([ True,  True, False])

# Array-wise Comparison

In [49]:
import numpy as np
a=[1,2,3]
b=[2,4,4]
c=[1,2,4]
np.array_equal(a,b)

False

In [50]:
import numpy as np
a=[1,2,3]
b=[2,4,4]
c=[1,2,4]
np.array_equal(a,c)

False

In [52]:
a=[1,2,3]
print(np.sum(a))
print(np.min(a))
print(np.max(a))

6
1
3
